obj-$(CONFIG_USER_PANEL_DRIVER) += omap-panel.o

obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_SAMSUNG_LTE430WQ_F0C) += panel-samsung-lte430wq-f0c.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_ZOOM2) += panel-zoom2.o
obj-$(CONFIG_PANEL_SHOLES) += panel-sholes.o
obj-$(CONFIG_PANEL_MAPPHONE) += panel-mapphone.o
obj-$(CONFIG_PANEL_MAPPHONE_HDTV) += panel-mapphone-hdtv.o
