#
# Copyright (C) 2009 Motorola, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# 02111-1307, USA
#
# Motorola 2009-Feb-18 - Initial Creation
#

MODULE_NAME = modem_pm_driver

obj-$(CONFIG_MODEM_PM_DRIVER) += $(MODULE_NAME).o
$(MODULE_NAME)-objs := modem_pm_driver_main.o

#obj-y           += modem_pm_driver_main.o
