# Makefile for OMAP3 hp3a driver

obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_lib.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_queue.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_ext.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_stats.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_histogram.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_af.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_raw.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_hardpipe.o
obj-$(CONFIG_VIDEO_OMAP3_HP3A) += hp3a_ioctl.o

EXTRA_CFLAGS += -Idrivers/media/video/isp
