#
# Makefile for the USB IPC drivers.
#
obj-$(CONFIG_USB_IPC)	+= usb-ipc.o
usb-ipc-objs :=	ipc_log.o ipc_data.o ipc_api.o ipc_dma.o

obj-$(CONFIG_USB_IPC_TEST)   += usb-ipc-test.o
usb-ipc-test-objs :=	ipc_api_test.o


